### ISSUE TITLE
build failure, missing source directory doctest/ghci-wrapper/src

### ISSUE THREAD

**Issue by mostalive** [hspec/sensei#20]
Long term fan of autotest(s) here, I'd like to start using it, but cabal install fails on me.

Looks like doctest directory is empty, is something missing in the git repository or am I missing something?

cabal output:
Build log ( /home/dockerx/sensei/.cabal-sandbox/logs/sensei-0.0.0.log ):
Configuring sensei-0.0.0...
Warning: 'hs-source-dirs: doctest/ghci-wrapper/src/' directory does not exist.
Building sensei-0.0.0...
Preprocessing library sensei-0.0.0...
setup-Simple-Cabal-1.20.0.3-x86_64-linux-ghc-7.8.4: can't find source for
Language/Haskell/GhciWrapper in src, doctest/ghci-wrapper/src/,
dist/dist-sandbox-81bba59c/build/autogen
cabal: Error: some packages failed to install:
sensei-0.0.0 failed during the building phase. The exception was:
ExitFailure 1

Thanks,

Willem

**Comment by soenkehahn** [comment]
My guess is you're missing:
``` bash
git submodule init
git submodule update
```

**Comment by mostalive** [comment]
Indeed. Thanks :-).

On 8 May 2015 16:02:03 BST, "Sönke Hahn" <notifications@github.com> wrote:
>My guess is you're missing:
>``` bash
>git submodule init
>git submodule update
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/hspec/sensei/issues/20#issuecomment-100263779

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.
