### ISSUE TITLE
`sensei` should work on arbitrary files that contain a `spec`.

### ISSUE THREAD

**Issue by soenkehahn** [hspec/sensei#22]
I often find myself trying something out in a single file (e.g. `Test.hs`) and then adding a `spec` in that single file. `sensei` won't execute that `spec` then, probably because it doesn't end in `...Spec.hs`.

I'm not sure this has no downsides, but I would propose that `sensei` should always try to execute a `spec :: Spec` top-level declaration, independent of the module name, file name or directory.

**Comment by sol** [comment]
Yes, I would had assumed it's already like that. But off it's not, let's change it. Patches welcome!

**Comment by sol** [comment]
@soenkehahn I can not reproduce the issue.  For me it works.  Can you give a minimal example?

**Comment by soenkehahn** [comment]
Can't reproduce either, closing.
