### ISSUE TITLE
`sensei` does not run the spec with `-XUnicodeSyntax` enabled

### ISSUE THREAD

**Issue by supki** [hspec/sensei#31]
With that extenstion being on, GHC likes to show `∷` in place of `::` in type signatures;  [`normalizeTypeSignatures`](https://github.com/hspec/sensei/blob/ccb093661ad71d698c0c246a85b77b71d04c2c88/src/Util.hs#L26) is woefully unprepared for that, which results in [`hasSpec`](https://github.com/hspec/sensei/blob/ccb093661ad71d698c0c246a85b77b71d04c2c88/src/Session.hs#L74) returning `False`.

:frowning:

**Comment by sol** [comment]
Damn, I think the right thing would really be to make sure that `~/.ghci` is not read.  But we still want `./.ghci`, and there is no way to tell `ghci` to do exactly that.
