### ISSUE TITLE
Dangling links make sensei give up file watching

### ISSUE THREAD

**Issue by fisx** [hspec/sensei#33]
It will keep running, but not react to any changes, even to changes to valid files.  Pressing `enter` still works.  Removing the dangling link and restarting is a good work-around.

**Comment by andorp** [comment]
Red error messages would be pleasant to the eye.

**Comment by sol** [comment]
This is a bug in `fsnotify` from what I can tell.

**Comment by sol** [comment]
I think this has been fixed upstream.
