### ISSUE TITLE
Pin down dependency versions and ghc version

### ISSUE THREAD

**Issue by soenkehahn** [hspec/sensei#39]
Currently the repo doesn't specify which compiler version and dependency versions to use to build `sensei` and run the test suite. I tried running the test suite and it fails with newer ghc versions, since the tests expect a certain format of ghc error messages, but those have changed. (The `travis` file specifies `ghc-7.10`, btw.) Given that this package provides a list of executables and no library there should be no downside in fully pinning down the compiler version and all dependencies.

What do people think about adding a `stack.yaml` file?

cc: @sol @amarpotghan @qoelet

**Comment by qoelet** [comment]
I certainly see no harm in taking that approach, pending @sol 's input.

**Comment by soenkehahn** [comment]
Oh, I realized I was still on tag `0.3.0`. `0.4.0` works with newer compilers. I'd still prefer having a stack file, but feel less passionate about that now.

**Comment by sol** [comment]
https://github.com/hspec/sensei/blob/main/.github/workflows/build.yml ensures that `sensei` works with recent compilers.  We also have a daily schedule so that we detect breakage in a timely manner.

Closing.
